import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.scss';
import NavbarLayout from '@/layout/navbar/navbar.layout';

const serifFont = localFont({
  src: '../fonts/PTSerif-Regular.ttf',
  variable: '--font-pt',
  weight: '100 900',
});

const serifBoldFont = localFont({
  src: '../fonts/PTSerif-Bold.ttf',
  variable: '--font-pt-bold',
  weight: '100 900',
});

const sansFont = localFont({
  src: '../fonts/OpenSans.ttf',
  variable: '--font-sans',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${serifFont.variable}  ${sansFont.variable}  ${serifBoldFont.variable} body`}
      >
        <NavbarLayout />

        {children}
      </body>
    </html>
  );
}
