backend:
  name: github
  repo: ethancanne/gias-hope-2

media_folder: 'public'
public_folder: '/'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: '/content/posts'
    create: true
    slug: '{{slug}}'
    fields:
      [
        { label: 'Title', name: 'title', widget: 'string' },
        { label: 'Image', name: 'image', widget: 'image' },
        { label: 'Date', name: 'date', widget: 'datetime' },
        { label: 'Author', name: 'author', widget: 'string' },
        { label: 'Category', name: 'category', widget: 'string' },
        { label: 'Content', name: 'content', widget: 'markdown' },
      ]

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Our Impact Page'
        name: 'ourImpactPage'
        file: '/content/pages/our-impact-page.md'
        fields:
          [
            {
              label: 'Page Description',
              name: 'pageDescription',
              widget: 'string',
            },
            {
              label: 'Large Page Image',
              name: 'largePageImage',
              widget: 'image',
            },
            {
              label: 'Mobile Page Image',
              name: 'mobilePageImage',
              widget: 'image',
            },
            {
              label: 'Featured Data',
              name: 'featuredData',
              widget: 'list',
              fields:
                [
                  { label: 'Text', name: 'text', widget: 'string' },
                  { label: 'Number', name: 'number', widget: 'number' },
                ],
            },
            {
              label: 'Impact Details Items',
              name: 'detailsData',
              widget: 'list',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Description',
                    name: 'description',
                    widget: 'markdown',
                  },
                  { label: 'Image', name: 'image', widget: 'image' },
                  {
                    label: 'Link',
                    name: 'link',
                    widget: 'string',
                    required: false,
                  },
                ],
            },
          ]

      - label: 'What We Do Page'
        name: 'whatWeDoPage'
        file: '/content/pages/what-we-do-page.md'
        fields:
          [
            {
              label: 'Page Description',
              name: 'pageDescription',
              widget: 'string',
            },
            {
              label: 'Large Page Image',
              name: 'largePageImage',
              widget: 'image',
            },
            {
              label: 'Mobile Page Image',
              name: 'mobilePageImage',
              widget: 'image',
            },
            {
              label: 'Visions',
              name: 'visions',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Icon', name: 'icon', widget: 'string' },
                  { label: 'ID', name: 'id', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                  {
                    label: 'Background Image',
                    name: 'backgroundImage',
                    widget: 'image',
                  },
                  {
                    label: 'Background Color',
                    name: 'backgroundColor',
                    widget: 'string',
                  },
                ],
            },
          ]
